on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  my-increment-semver-job:
    runs-on: ubuntu-latest
    name: A job to test incrementing the version of a repository
    steps:

#      Note Checkout is required for ${GITHUB_WORKSPACE} to be not empty
      - name: Checkout
        uses: actions/checkout@v1


#     Examples
      - name: Increment Step Patch
        id: increment-semver-patch
        uses: Benbentwo/increment-semver@master
        with:
          version-level: '-p'

      - name: Increment Step Minor
        id: increment-semver-minor
        uses: Benbentwo/increment-semver@master
        with:
          version-level: '-m'

      - name: Increment Step Major
        id: increment-semver-major
        uses: Benbentwo/increment-semver@master
        with:
          version-level: '-M'

      # Use the output from the `Increment Step X` step
      - name: Get the output version
        run: |
          echo "The new patch version was ${{ steps.increment-semver-patch.outputs.version }}"
          echo "The new minor version was ${{ steps.increment-semver-minor.outputs.version }}"
          echo "The new Major version was ${{ steps.increment-semver-major.outputs.version }}"
