name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          
      - name: DisplayPythonversion
        run: python -c "import sys; print(sys.version)"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel venv-pack 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Lint with Ruff
        run: |
            pip install ruff
            ruff --format=github --target-version=py37 .
        continue-on-error: true
        
      - name: Build package
        run: |
          python -m venv pyspark_venvsource
          source pyspark_venvsource/bin/activate
          venv-pack -f -o pyspark_venv.tar.gz
          ls -la
          
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip output
        run: zip -qq -r main_app.zip ${{ github.workspace }}/main_app/
        working-directory: ${{ github.workspace }}/main_app/
                    
      - name: Deploy tar to AWS S3
        uses: qoqa/action-s3-cp@v1.1
        env:
           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: 'us-east-1'
           AWS_S3_PATH: '/Sample/'
           FILE: '${{ github.workspace }}/target/*.zip'
           

