---
name: Python package
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: DisplayPythonversion
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel venv-pack 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --format=github --target-version=py37 .
        continue-on-error: true
      - name: Build package
        run: |
          python -m venv pyspark_venvsource
          source pyspark_venvsource/bin/activate
          venv-pack -f -o pyspark_venv.tar.gz
          ls -la
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip output
        run: zip -qq -r main_app.zip ${{ github.workspace }}/main_app/
        working-directory: ${{ github.workspace }}/main_app/
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      # This command adds a new server configuration to the JFrog CLI   
      - run: |
         export SERVER_ID="test"
         jf c add $SERVER_ID --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false
         
     # This action creates a new test file and uploads it to Artifactory   
      - name: Push Build to Artifactory
        run: |
          echo "test file " > test.txt
          export BUILD_NAME="my-build"
          export BUILD_MODULE="my-module"
          export BUILD_NUMBER="1"


          export PATH_TO_DIRECTORY="name/version/dates"
        
          jf rt upload "test.txt" apcdl-pypi-local/$PATH_TO_DIRECTORY --build-name $BUILD_NAME --build-number $BUILD_NUMBER --module $BUILD_MODULE


   # This action publishes the build information to Artifactory and deletes older builds
      - name: Build to Artifactory
        run: |
          jf rt build-publish $BUILD_NAME $BUILD_NUMBER
